export const FETCH_TEAM_COMPOSITION_REQUESTED =
  'teamComposition/FETCH_TEAM_COMPOSITION_REQUESTED'
export const FETCH_TEAM_COMPOSITION_SUCCEEDED =
  'teamComposition/FETCH_TEAM_COMPOSITION_SUCCEEDED'
export const FETCH_TEAM_COMPOSITION_FAILED =
  'teamComposition/FETCH_TEAM_COMPOSITION_FAILED'
